<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Kinch' => '',
    'WCA ID' => '',
    '(was)' => '（過去）',
    '100 Persons' => '100位まで',
    '1000 Persons' => '1000位まで',
    'All' => 'すべて',
    'All Persons' => 'すべて',
    'Average' => '平均',
    'Best' => 'ベスト',
    'Competition' => '大会',
    'Continents' => '大陸',
    'Countries' => '国',
    'Country' => '国',
    'Event' => '種目',
    'Female' => '女性',
    'First' => '最初へ',
    'Gender' => '性別',
    'Home' => 'ホーム',
    'Kinch Rank - Continents' => 'Kinchランキング - 大陸',
    'Kinch Rank - Countries' => 'Kinchランキング - 国',
    'Kinch Rank - Persons' => 'Kinchランキング - 競技者',
    'Last' => '最後へ',
    'Last Update: ' => '最新更新',
    'Male' => '男性',
    'Name' => '名前',
    'Name parts or WCA ID' => '名あるいはWCA ID（一部）',
    'Neither' => '無',
    'Next' => '次へ',
    'Overall' => 'スコア',
    'Person' => '競技者',
    'Persons' => '競技者',
    'Previous' => '前へ',
    'Rank' => '順位',
    'Region' => '地域',
    'Show' => '件数',
    'Submit' => '確認',
    'Unknown' => 'わからない',
    'WCA Profile - ' => 'WCA プロフィール',
    'WCA Profile - Person Not Found' => 'WCA プロフィール　- 該当なし',
    'WCA Statistics' => 'WCA統計',
    'World' => '世界',
    '{count,plural,=1{# person} other{# persons}} matching: "{query}"' => '{count,plural,=0{一致する結果がありません} other{#人見つかりました}}：「{query}」',
    '{days,plural,=1{# day ago} =0{Today} other{# days ago}}' => '{days,plural,=0{今日} other{{days,number,0}日前}}',
];
