<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex/extract-db' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2x2 Cube' => '2x2キューブ',
    '3x3 blindfolded' => '3x3目隠し',
    '3x3 fewest moves' => '3x3最少手数',
    '3x3 multi blind' => '3x3複数目隠し',
    '3x3 multi blind old' => '旧3x3複数目隠し',
    '3x3 one-handed' => '3x3片手',
    '3x3 with feet' => '3x3足',
    '4x4 Cube' => '4x4キューブ',
    '4x4 Cube: Blindfolded' => '4x4キューブ: 目隠し',
    '4x4 blindfolded' => '4x4目隠し',
    '5x5 Cube' => '5x5キューブ',
    '5x5 Cube: Blindfolded' => '5x5キューブ: 目隠し',
    '5x5 blindfolded' => '5x5目隠し',
    '6x6 Cube' => '6x6キューブ',
    '7x7 Cube' => '7x7キューブ',
    'Master Magic' => 'マスターマジック',
    'Megaminx' => 'メガミンクス',
    'Pyraminx' => 'ピラミンクス',
    'Rubik\'s Clock' => 'ルービッククロック',
    'Rubik\'s Cube' => 'ルービックキューブ',
    'Rubik\'s Cube: Blindfolded' => 'ルービックキューブ: 目隠し',
    'Rubik\'s Cube: Fewest moves' => 'ルービックキューブ最少手数',
    'Rubik\'s Cube: Multi blind old style' => '旧ルービックキューブ: 複数目隠し',
    'Rubik\'s Cube: Multiple Blindfolded' => 'ルービックキューブ: 複数目隠し',
    'Rubik\'s Cube: One-handed' => 'ルービックキューブ片手',
    'Rubik\'s Cube: With feet' => 'ルービックキューブ足',
    'Rubik\'s Magic' => 'ルービックマジック',
    'Skewb' => 'スキューブ',
    'Square-1' => 'スクエア1',
];
