<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex/extract-db' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '3x3x3 Cube' => '3x3x3キューブ',
    '3x3x3 Multi-Blind Old Style' => '旧3x3x3キューブ: 複数目隠し',
    'Clock' => 'クロック',
    'Magic' => 'マジック',
    '2x2x2 Cube' => '2x2x2キューブ',
    '3x3x3 Blindfolded' => '3x3x3目隠し',
    '3x3x3 Fewest Moves' => '3x3x3最少手数',
    '3x3x3 Multi-Blind' => '3x3x3複数目隠し',
    '3x3x3 One-Handed' => '3x3x3片手',
    '3x3x3 With Feet' => '3x3x3足',
    '4x4x4 Blindfolded' => '4x4x4目隠し',
    '4x4x4 Cube' => '4x4x4キューブ',
    '5x5x5 Blindfolded' => '5x5x5目隠し',
    '5x5x5 Cube' => '5x5x5キューブ',
    '6x6x6 Cube' => '6x6x6キューブ',
    '7x7x7 Cube' => '7x7x7キューブ',
    'Master Magic' => 'マスターマジック',
    'Megaminx' => 'メガミンクス',
    'Pyraminx' => 'ピラミンクス',
    'Skewb' => 'スキューブ',
    'Square-1' => 'スクエア1',
];
