<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Kinch' => '',
    'WCA ID' => '',
    '{count,plural,=1{# person} other{# persons}} matching: "{query}"' => '{count,plural,=0{没有人} other{#个人}}符合：“{query}”',
    '(was)' => '（曾经是）',
    'All' => '所有',
    'Average' => '平均',
    'Best' => '最好',
    'Competition' => '比赛',
    'Continents' => '洲',
    'Countries' => '国家',
    'Country' => '国家',
    'Date' => '日期',
    'Days' => '天数',
    'Event' => '项目',
    'Female' => '女',
    'Gender' => '性别',
    'Home' => '主页',
    'Kinch Rank - Continents' => 'Kinch排名 - 大洲',
    'Kinch Rank - Countries' => 'Kinch排名 - 国家',
    'Last Update: ' => '最后更新：',
    'Male' => '男',
    'Name' => '姓名',
    'Name parts or WCA ID' => '姓名或WCA ID(部分)',
    'Neither' => '无',
    'Oldest Standing Personal Records' => '保持时间最长的个人最好成绩',
    'Overall' => '总分',
    'Persons' => '选手',
    'Rank' => '排名',
    'Region' => '地区',
    'Submit' => '提交',
    'Unknown' => '未知',
    'WCA Profile - ' => 'WCA个人资料 - ',
    'WCA Profile - Person Not Found' => 'WCA个人资料 - 未找到相关选手',
    'WCA Statistics' => 'WCA 数据统计',
    'World' => '世界',
];
