<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex/extract-db' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2x2x2 Cube' => '2x2x2魔方',
    '3x3x3 Blindfolded' => '3x3x3盲拧',
    '3x3x3 Fewest Moves' => '3x3x3最少步',
    '3x3x3 Multi-Blind' => '3x3x3多盲',
    '3x3x3 One-Handed' => '3x3x3单手',
    '3x3x3 With Feet' => '3x3x3脚拧',
    '4x4x4 Blindfolded' => '4x4x4盲拧',
    '4x4x4 Cube' => '4x4x4魔方',
    '5x5x5 Blindfolded' => '5x5x5盲拧',
    '5x5x5 Cube' => '5x5x5魔方',
    '6x6x6 Cube' => '6x6x6魔方',
    '7x7x7 Cube' => '7x7x7魔方',
    'Master Magic' => '十二片魔板',
    'Megaminx' => '五魔方',
    'Pyraminx' => '金字塔',
    'Rubik\'s Clock' => '魔表',
    'Rubik\'s Cube' => '三阶魔方',
    'Rubik\'s Cube: Multi blind old style' => '三阶多个盲拧（旧规则）',
    'Rubik\'s Magic' => '八片魔板',
    'Skewb' => '斜转魔方',
    'Square-1' => 'Square-1魔方',
];
