<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2x2 Cube' => '2x2魔方',
    '3x3 blindfolded' => '3x3盲拧',
    '3x3 fewest moves' => '3x3最少步',
    '3x3 multi blind' => '3x3多盲',
    '3x3 multi blind old' => '3x3多盲(旧)',
    '3x3 one-handed' => '3x3单手',
    '3x3 with feet' => '3x3脚拧',
    '4x4 Cube' => '4x4魔方',
    '4x4 Cube: Blindfolded' => '四阶盲拧',
    '4x4 blindfolded' => '4x4盲拧',
    '5x5 Cube' => '5x5魔方',
    '5x5 Cube: Blindfolded' => '五阶盲拧',
    '5x5 blindfolded' => '5x5盲拧',
    '6x6 Cube' => '六阶魔方',
    '7x7 Cube' => '七阶魔方',
    'Master Magic' => '十二片魔板',
    'Megaminx' => '五魔方',
    'Pyraminx' => '金字塔',
    'Rubik\'s Clock' => '魔表',
    'Rubik\'s Cube' => '三阶魔方',
    'Rubik\'s Cube: Blindfolded' => '三阶盲拧',
    'Rubik\'s Cube: Fewest moves' => '三阶最少步',
    'Rubik\'s Cube: Multi blind old style' => '三阶多个盲拧（旧规则）',
    'Rubik\'s Cube: Multiple Blindfolded' => '三阶多个盲拧',
    'Rubik\'s Cube: One-handed' => '三阶单手',
    'Rubik\'s Cube: With feet' => '三阶脚拧',
    'Rubik\'s Magic' => '八片魔板',
    'Skewb' => '斜转魔方',
    'Square-1' => 'Square-1魔方',
];
