<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Persons' => '所有選手',
    'First' => '首頁',
    'Kinch' => '',
    'Kinch Rank - Persons' => 'Kinch排名 － 選手',
    'Last' => '末頁',
    'Next' => '次頁',
    'Previous' => '前頁',
    'WCA ID' => '',
    '(was)' => '（曾經是）',
    '100 Persons' => '100名選手',
    '1000 Persons' => '1000名選手',
    'All' => '所有',
    'Average' => '平均',
    'Best' => '最好',
    'Competition' => '比賽',
    'Continents' => '洲',
    'Countries' => '國家',
    'Country' => '國家',
    'Event' => '項目',
    'Female' => '女',
    'Gender' => '性別',
    'Home' => '首頁',
    'Kinch Rank - Continents' => 'Kinch排名 － 大洲',
    'Kinch Rank - Countries' => 'Kinch排名 － 國家',
    'Last Update: ' => '最後更新：',
    'Male' => '男',
    'Name' => '姓名',
    'Name parts or WCA ID' => '姓名或WCA ID（部分）',
    'Neither' => '無',
    'Overall' => '總分',
    'Person' => '選手',
    'Persons' => '選手',
    'Rank' => '順位',
    'Region' => '地區',
    'Show' => '顯示',
    'Submit' => '遞交',
    'Unknown' => '未知',
    'WCA Profile - ' => 'WCA個人檔案 － ',
    'WCA Profile - Person Not Found' => 'WCA個人檔案 － 選手未找到',
    'WCA Statistics' => 'WCA數據統計',
    'World' => '世界',
    '{count,plural,=1{# person} other{# persons}} matching: "{query}"' => '{count,plural,=0{沒有人} other{#個人}}符合：“{query}”',
    '{days,plural,=1{# day ago} =0{Today} other{# days ago}}' => '{days,plural,=0{今天} other{{days,number,0}天前}}',
];
