<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex/extract-db' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2x2x2 Cube' => '2x2x2方塊',
    '3x3x3 Blindfolded' => '3x3x3盲解',
    '3x3x3 Fewest Moves' => '3x3x3最少步數解',
    '3x3x3 Multi-Blind' => '3x3x3多顆盲解',
    '3x3x3 One-Handed' => '3x3x3單手解',
    '3x3x3 With Feet' => '3x3x3腳解',
    '4x4x4 Blindfolded' => '4x4x4盲解',
    '4x4x4 Cube' => '4x4x4方塊',
    '5x5x5 Blindfolded' => '5x5x5盲解',
    '5x5x5 Cube' => '5x5x5方塊',
    '6x6x6 Cube' => '6x6x6方塊',
    '7x7x7 Cube' => '7x7x7方塊',
    'Square-1' => 'Square-1方塊',
    'Master Magic' => '十二片魔板',
    'Megaminx' => '12面體',
    'Pyraminx' => '金字塔',
    'Rubik\'s Clock' => '魔錶',
    'Rubik\'s Cube' => '三階方塊',
    'Rubik\'s Cube: Multi blind old style' => '三階方塊多顆盲解(舊)',
    'Rubik\'s Magic' => '八片魔板',
    'Skewb' => '斜轉方塊',
];
