<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(was)' => '',
    'All' => '',
    'Average' => '',
    'Best' => '',
    'Competition' => '',
    'Continents' => '',
    'Countries' => '',
    'Country' => '',
    'Date' => '',
    'Days' => '',
    'Event' => '',
    'Female' => '',
    'Gender' => '',
    'Home' => '',
    'Kinch' => '',
    'Kinch Rank - Continents' => '',
    'Kinch Rank - Countries' => '',
    'Last Update: ' => '',
    'Male' => '',
    'Name' => '',
    'Name parts or WCA ID' => '',
    'Neither' => '',
    'Oldest Standing Personal Records' => '',
    'Overall' => '',
    'Persons' => '',
    'Rank' => '',
    'Region' => '',
    'Submit' => '',
    'Unknown' => '',
    'WCA ID' => '',
    'WCA Profile - ' => '',
    'WCA Profile - Person Not Found' => '',
    'WCA Statistics' => '',
    'World' => '',
    '{count,plural,=1{# person} other{# persons}} matching: "{query}"' => '',
    '{days,plural,=1{# day ago} =0{Today} other{# days ago}}' => '',
];
