<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message-ex' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2x2 Cube' => '',
    '3x3 blindfolded' => '',
    '3x3 fewest moves' => '',
    '3x3 multi blind' => '',
    '3x3 multi blind old' => '',
    '3x3 one-handed' => '',
    '3x3 with feet' => '',
    '4x4 Cube' => '',
    '4x4 Cube: Blindfolded' => '',
    '4x4 blindfolded' => '',
    '5x5 Cube' => '',
    '5x5 Cube: Blindfolded' => '',
    '5x5 blindfolded' => '',
    '6x6 Cube' => '',
    '7x7 Cube' => '',
    'Master Magic' => '',
    'Megaminx' => '',
    'Pyraminx' => '',
    'Rubik\'s Clock' => '',
    'Rubik\'s Cube' => '',
    'Rubik\'s Cube: Blindfolded' => '',
    'Rubik\'s Cube: Fewest moves' => '',
    'Rubik\'s Cube: Multi blind old style' => '',
    'Rubik\'s Cube: Multiple Blindfolded' => '',
    'Rubik\'s Cube: One-handed' => '',
    'Rubik\'s Cube: With feet' => '',
    'Rubik\'s Magic' => '',
    'Skewb' => '',
    'Square-1' => '',
];
